### ISSUE TITLE
Unknown instruction: ARG

### ISSUE THREAD

**Issue by lucasvc** [openanalytics/docker-editor#3]
As Dockerfile reference states, there is a new instruction called [`ARG`](https://docs.docker.com/engine/reference/builder/#arg), but current version shows error when used in files.

**Comment by tverbeke** [comment]
Many thanks for the report. Our Docker editor will be included in the next release of the Eclipse Docker Tools (see https://twitter.com/akurtakov/status/712956464114110465). I will look to report it there.

**Comment by Vadus** [comment]
Any news about that ? I've installed the docker-editor in eclipse today over marketplace. I got the version   Dockerfile Editor	1.0.0.201506222127	from there. With this version I get the mentioned error, too.

Is there a more recent update site ?

**Comment by tverbeke** [comment]
It is part of the tools one can directly install from Eclipse using the Eclipse Repository and part of the 'Docker Tooling'

![docker-tooling](https://user-images.githubusercontent.com/5047312/28463714-237a03b8-6e22-11e7-88a9-31a617e7fc4b.png)
